<?php
/**
 * Layout variables
 *
 * - FWK_PAGE_TITLE
 */
$PAGE_TITLE = "nitronet - Le blog de neiluJ";

include __DIR__ .'/../header.phtml';
use Nitronet\models\Publication;

?>
<div class="container" id="main">
    <ul>
        <?php foreach ($this->articles as $article): ?>
        <li>
            <p class="rightside rkktt"><?php echo $article->dateFormat(Publication::DATEFIELD_CREATED_AT, "d F @ H:i:s"); ?></p>

            <h2><a href="<?php echo $this->_helper->url('ArticleView', array('articleSlug' => $article->getSlug())); ?>"><?php echo htmlspecialchars($article->getTitle()); ?></a></h2>

            <p class="post"><?php echo $article->getExcerp(); ?> [<a href="<?php echo $this->_helper->url('ArticleView', array('articleSlug' => $article->getSlug())); ?>">read</a>]</p>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php

include __DIR__ .'/../footer.phtml';

?>