<?php
/**
 * Layout variables
 *
 * - FWK_PAGE_TITLE
 */
$PAGE_TITLE = "nitronet - Le blog de neiluJ";

include __DIR__ .'/../header.phtml';
?>
<div class="container" id="main">
    <ul>
        <?php foreach ($this->articles as $article): ?>
        <li>
            <p class="rightside rkktt"><?php echo $article->getDateRelativeCreated(); ?></p>

            <h2><a href="<?php echo $this->basePath; ?>/index.php/article/<?php echo $article->getSlug(); ?>"><?php echo htmlspecialchars($article->getTitle()); ?></a></h2>
            
            <p class="post"><?php echo $article->getExcerp(); ?> [<a href="<?php echo $this->basePath; ?>/index.php/article/<?php echo $article->getSlug(); ?>">read</a>]</p>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php

include __DIR__ .'/../footer.phtml';

?>