<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $PAGE_TITLE; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo $this->basePath; ?>/css/reset.css" rel="stylesheet">
    <link href="<?php echo $this->basePath; ?>/css/style.css" rel="stylesheet">

    <link rel="stylesheet" href="<?php echo $this->basePath; ?>/hljs/styles/github.css">
    <script src="<?php echo $this->basePath; ?>/hljs/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
        
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <!-- <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
    -->
  </head>

  <body>
    <div class="container" id="head">
        <p class="rightside rkktt">
            <a href="https://github.com/neiluJ"><img src="<?php echo $this->basePath; ?>/images/social/github.png" title="Github" alt="gh" /></a>
            <a href="http://twitter.com/neiluj34"><img src="<?php echo $this->basePath; ?>/images/social/twitter.png" title="Twitter" alt="tw" /></a>
            <a href="#"><img src="<?php echo $this->basePath; ?>/images/social/linkedin.png" title="LinkedIn" alt="in" /></a>
            <a href="<?php echo $this->basePath; ?>/rss"><img src="<?php echo $this->basePath; ?>/images/social/rss.png" title="RSS Feed" alt="rss" /></a>
        </p>
        <h1><a href="<?php echo $this->basePath; ?>">nitronet</a> <span>Le weblog de <a href="http://neiluj.pro">neiluJ</a>, développeur web.</span></h1>
    </div>
