<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $PAGE_TITLE; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <?php foreach($this->_helper->assets(array(
        '@Nitronet/themes/origin/assets/css/reset.css',
        '@Nitronet/themes/origin/assets/css/style.css',
        '@Nitronet/themes/origin/assets/hljs/styles/github.css'
    ), array('cssrewrite'), 'site') as $src): ?>
    <link rel="stylesheet" href="<?php echo $src; ?>">
    <?php endforeach; ?>
    
    <?php foreach($this->_helper->assets(array(
        '@Nitronet/themes/origin/assets/hljs/highlight.pack.js',
    ), array('cssrewrite'), 'hljs.pack') as $src): ?>
    <script type="text/javascript" src="<?php echo $src; ?>"></script>
    <?php endforeach; ?>
    
    <script>hljs.initHighlightingOnLoad();</script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="alternate" type="application/rss+xml" title="Nitronet RSS Feed" href="/rss.xml" />
  </head>

  <body>
    <div class="container" id="head">
        <p class="rightside rkktt">
            <a href="https://github.com/neiluJ"><img src="<?php echo array_shift($this->_helper->assets('@Nitronet/themes/origin/assets/images/social/github.png', array(), 'github')); ?>" title="Github" alt="gh" /></a>
            <a href="http://twitter.com/neiluj34"><img src="<?php echo array_shift($this->_helper->assets('@Nitronet/themes/origin/assets/images/social/twitter.png', array(), 'twitter')); ?>" title="Twitter" alt="tw" /></a>
            <a href="<?php echo $this->_helper->url('RssFeed'); ?>"><img src="<?php echo array_shift($this->_helper->assets('@Nitronet/themes/origin/assets/images/social/rss.png', array(), 'rss')); ?>" title="RSS Feed" alt="rss" /></a>
        </p>
        <h1><a href="<?php echo $this->_helper->url('Home'); ?>">nitronet</a> <span>Le weblog de <a href="http://neiluj.pro">neiluJ</a>, développeur web.</span></h1>
    </div>
